# Generated by Django 5.0.7 on 2024-08-01 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingredient", "0002_ingredient_created_by_ingredient_is_custom_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="middle",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ingredient.ingremiddle",
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="sub",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ingredient.ingresub",
            ),
        ),
    ]
