# Generated by Django 5.0.7 on 2024-07-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app_user",
            name="user_id",
            field=models.UUIDField(unique=True),
        ),
    ]
