# Generated by Django 5.0.7 on 2024-07-29 17:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="app_user",
            options={},
        ),
        migrations.AlterModelManagers(
            name="app_user",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="app_user",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="app_user",
            name="is_activate",
        ),
        migrations.RemoveField(
            model_name="app_user",
            name="last_name",
        ),
        migrations.AddField(
            model_name="app_user",
            name="refresh_token",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="app_user",
            name="date_joined",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="app_user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="app_user",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="app_user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="app_user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="app_user",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="app_user",
            name="role",
            field=models.CharField(
                choices=[("ADMIN", "관리자"), ("USER", "사용자")],
                default="USER",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="app_user",
            name="user_id",
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name="OutstandingToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outstanding_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
