# Generated by Django 5.0.7 on 2024-07-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_user", "0002_alter_app_user_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="app_user",
            options={},
        ),
        migrations.AlterModelManagers(
            name="app_user",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="app_user",
            name="email",
        ),
        migrations.RemoveField(
            model_name="app_user",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="app_user",
            name="is_activate",
        ),
        migrations.RemoveField(
            model_name="app_user",
            name="last_name",
        ),
        migrations.AlterField(
            model_name="app_user",
            name="date_joined",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="app_user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="app_user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="app_user",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
