# Generated by Django 5.0.7 on 2024-08-02 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_user", "0002_alter_app_user_options_alter_app_user_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="app_user",
            name="email_verification_token",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="app_user",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
    ]
