# Generated by Django 5.0.7 on 2024-07-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_user", "0003_remove_app_user_password_hash"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="app_user",
            name="name",
        ),
        migrations.AlterField(
            model_name="app_user",
            name="id",
            field=models.UUIDField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name="app_user",
            name="user_id",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="app_user",
            name="username",
            field=models.CharField(max_length=255),
        ),
    ]
