# Generated by Django 5.0.7 on 2024-07-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_user", "0003_alter_app_user_options_alter_app_user_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="app_user",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
