# Generated by Django 5.0.7 on 2024-07-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_user", "0004_app_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app_user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
