# Generated by Django 5.0.7 on 2024-08-01 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0002_recipe_created_at_recipe_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cookingattribute",
            name="main_ingre",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="recipe.cookingmainingre"),
        ),
        migrations.AlterField(
            model_name="cookingattribute",
            name="method",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="recipe.cookingmethod"),
        ),
        migrations.AlterField(
            model_name="cookingattribute",
            name="situation",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="recipe.cookingsituation"),
        ),
        migrations.AlterField(
            model_name="cookingattribute",
            name="type",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="recipe.cookingtype"),
        ),
    ]
