# Generated by Django 5.0.7 on 2024-08-01 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0004_alter_cookingattribute_name_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cookingattribute",
            unique_together=set(),
        ),
    ]
