# Generated by Django 5.0.7 on 2024-08-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0005_alter_cookingattribute_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="nick_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
