# Generated by Django 5.0.7 on 2024-08-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0006_alter_recipe_nick_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cookingmainingre",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="cookingmethod",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="cookingnamelist",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="cookingsituation",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="cookingtype",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
