# Generated by Django 5.0.7 on 2024-08-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "recipe",
            "0007_alter_cookingmainingre_name_alter_cookingmethod_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="nick_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
