# version: '3.12'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:  # .env 파일에서 환경 변수 읽어오기
      - .env
    command: python manage.py runserver 0.0.0.0:8000