# Generated by Django 5.0.7 on 2024-07-25 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ingredient", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Refrigerator",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_activate", models.BooleanField(default=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="RefrigeratorIngredientList",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("expiration_date", models.DateField()),
                (
                    "ingredient",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ingredient.ingredient"),
                ),
                (
                    "refrigerator",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="refrigerator.refrigerator"),
                ),
            ],
        ),
    ]
