name: Code Style Check  # 워크플로우 이름 설정

# 이벤트 트리거 설정 (푸시 및 풀 리퀘스트 발생 시 워크플로우 실행)
on:
  push:
    branches: ['**']  # 모든 브랜치에 대한 푸시 이벤트
  pull_request:
    branches: ['**']  # 모든 브랜치에 대한 풀 리퀘스트 이벤트

# 작업 정의 (lint 작업)
jobs:
  lint:
    runs-on: ubuntu-latest  # 작업 실행 환경 (Ubuntu 최신 버전)
    steps:
      - uses: actions/checkout@v3  # 코드 체크아웃 (저장소 코드 가져오기)

      # Python 환경 설정
      - name: Set up Python
        uses: actions/setup-python@v4  # actions/setup-python 액션 사용
        with:
          python-version: '3.12'  # 사용할 Python 버전 (3.12)

      # 의존성 설치 (Black, isort)
      - name: Install dependencies
        run: |  # 실행할 명령어 (여러 줄일 경우 | 사용)
          python -m pip install --upgrade pip  # pip 최신 버전으로 업그레이드
          pip install black isort  # Black 및 isort 설치

      # 코드 스타일 검사 도구 실행
      - name: Run black  # Black 실행 (코드 포맷팅 검사)
        run: black --check .  # Black 실행, --check 옵션으로 포맷팅 오류만 검사
      - name: Run isort  # isort 실행 (import 문 정렬 검사)
        run: isort --check-only .  # isort 실행, --check-only 옵션으로 정렬 오류만 검사
