name: Deploy to EC2 with Docker Compose and Migration

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Install Docker on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ec2-43-203-195-173.ap-northeast-2.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            sudo apt-get update
            sudo apt-get install docker.io -y
            sudo service docker start
            sudo usermod -a -G docker $USER

      - name: Install Docker Compose on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ec2-43-203-195-173.ap-northeast-2.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            sudo curl -L "https://github.com/docker/compose/releases/download/v2.18.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose

      - name: Run database migrations
        uses: appleboy/ssh-action@master
        with:
          host: ec2-43-203-195-173.ap-northeast-2.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            ls -al
            cd /home/ubuntu/my-app # 프로젝트 디렉토리로 이동 (실제 경로로 수정 필요)
            docker-compose run web python manage.py migrate  # 마이그레이션 실행
        env:
          RDS_DATABASE: ${{ secrets.RDS_DATABASE }}
          RDS_USERNAME: ${{ secrets.RDS_USERNAME }}
          RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
          RDS_HOSTNAME: ${{ secrets.RDS_HOSTNAME }}
          RDS_PORT: ${{ secrets.RDS_PORT }}

      - name: Build and run Docker Compose on EC2
        uses: appleboy/ssh-action@master
        with:
            host: ec2-43-203-195-173.ap-northeast-2.compute.amazonaws.com
            username: ubuntu
            key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
            script: |
                cd /home/ubuntu/my-app
                ls -al # 현재 작업 디렉토리 파일 목록 출력
                docker-compose --version # Docker Compose 버전 확인
                docker-compose down 
                docker-compose build --build-arg DB_PASSWORD=${{ secrets.DB_PASSWORD }}
                docker-compose up -d
        env:
          RDS_DATABASE: ${{ secrets.RDS_DATABASE }}
          RDS_USERNAME: ${{ secrets.RDS_USERNAME }}
          RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
          RDS_HOSTNAME: ${{ secrets.RDS_HOSTNAME }}
          RDS_PORT: ${{ secrets.RDS_PORT }}
